name: hello_dart_web
version: 0.0.1
description: Hello Dart for Web

dependencies:

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  browser_launcher: ^0.1.5
  test: ^1.14.3
  webdriver: any

# run:
# "pub get" to get all dependencies
# webdev serve
# "pub run test"